lora:
  r:              8
  lora_alpha:     16
  lora_dropout:   0.05
  target_modules: null
  task_type:      "SEQ_2_SEQ_LM"
  bias:           "none"

quantization:
  use_4bit:                   true
  bnb_4bit_quant_type:       "nf4"
  bnb_4bit_compute_dtype:    "float16"
  bnb_4bit_use_double_quant:  true
